# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - RUN_PHPCS="no"

matrix:
  include:
    - php: 5.3
      env: RUN_PHPCS="yes"
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0

before_script:
  # Make sure all dev dependencies are installed
  - composer install

script:
  - if [ "$RUN_PHPCS" == "yes" ]; then then vendor/bin/phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla --ignore=./*tmpl/* administrator/components/com_patchtester; fi
