# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - RUN_PHPCS="no"
    - UPDATE_CROWDIN="no"
  secure: DafjnG9HxBI2mbDVg1C1yS/VYt4Et1WA/iolVkNJNgnrhYGFsGthowRPXNzRUh4AisrSQcozF29p8tZFMNCdFxAV4SmgO/yOMfXaJP4DvhdOj2NHzdRCfRu7LjU/SSDe1DGCmqzURclHrxWylcw5nU/o6/0ceviqQIhN9PFWyUc=

matrix:
  include:
    - php: 5.3
      env: RUN_PHPCS="yes"
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
      env: UPDATE_CROWDIN="yes"

before_script:
  # Make sure all dev dependencies are installed
  - composer install

script:
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla --ignore=./*tmpl/* administrator/components/com_patchtester; fi

after_success:
 - if [ "$UPDATE_CROWDIN" == "yes" ]; then ./travis-lang-update.sh; fi
