export_languages: ["en-GB"]
files:
  - source: /administrator/components/com_patchtester/language/en-GB/com_patchtester.ini
    translation: /administrator/components/com_patchtester/language/%locale%/com_patchtester.ini
    update_option: update_as_unapproved
  - source: /administrator/components/com_patchtester/language/en-GB/com_patchtester.sys.ini
    translation: /administrator/components/com_patchtester/language/%locale%/com_patchtester.sys.ini
    update_option: update_as_unapproved
