project_identifier: joomla-patchtester
api_key_env: 'CROWDIN_API_KEY'
base_path: ./administrator/components/com_patchtester/language

files:
  -
    source: /en-GB/en-GB.com_patchtester.ini
    translation: /%locale%/%locale%.com_patchtester.ini
  -
    source: /en-GB/en-GB.com_patchtester.sys.ini
    translation: /%locale%/%locale%.com_patchtester.sys.ini
